# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-28 18:47
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181228_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pud_date',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
