# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0012_technologies_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='myprojects',
            name='project_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webpage.ProjectClasses'),
            preserve_default=False,
        ),
    ]
