# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-12-09 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0013_auto_20181209_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprojects',
            name='image',
            field=models.ImageField(default='', upload_to=b'static/projects'),
            preserve_default=False,
        ),
    ]
