# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-04 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0015_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprojects',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
