# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-04 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0017_myprojects_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojects',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='myprojects',
            name='slug',
            field=models.SlugField(blank=True, default=b''),
        ),
    ]
