# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-04 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0018_auto_20190104_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprojects',
            name='technologies',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
