# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0019_myprojects_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprojects',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
